version: "3.9"
services:
  backend:
    build: ./backend
    container_name: devsecops-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: devsecops-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
